name: Lint Action

on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: write
      deployments: none
      id-token: none
      issues: none
      discussions: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint
